[project]
name = "example-run-in-aws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "playwright>=1.49.1",
    "pytest>=8.3.4",
    "pytest-html>=4.1.1",
    "pytest-playwright>=0.6.2",
]
